version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:3000
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:3000
    networks:
      - healthsync-net
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - OPENAI_KEY=${OPENAI_KEY}
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - healthsync-net

networks:
  healthsync-net:
    driver: bridge